### ISSUE TITLE
Typescript definitions for chrome-promise

### ISSUE THREAD

**Issue by ethanroday** [tfoxy/chrome-promise#11]
Would be great to have Typescript type definitions available for this package.
Could probably just use the [@types/chrome](https://www.npmjs.com/package/@types/chrome) definitions with minimal changes.

**Comment by tfoxy** [comment]
Will add them in the following days.

**Comment by tfoxy** [comment]
Hi. Sorry for the long delay. I've been using Typescript lately so now I'm more familiar with it.

What I'm trying to do now is to compile the declarations file from @types/chrome to an AST and then changing the declarations so that they use promises.

**Comment by fedoranimus** [comment]
Any updates on this?

**Comment by tfoxy** [comment]
I didn't have much time to work on side projects this year. But this week I'm moving closer to where I work. So I'm planning to catch up with all the things I've been postponing. And this is one of them. So expect a release in the near future.

**Comment by fedoranimus** [comment]
Excellent, look forward to it!

**Comment by tfoxy** [comment]
Working on this right now, just to let you know.

**Comment by tfoxy** [comment]
After a really long time, it's finally done! You can download the 2.1.0 version. Some APIs are missing because they are not present in `@types/chrome`. If there are some errors in the definitions, please create a new issue.

Hope this helps!

**Comment by errorx666** [comment]
It looks like the `Storage` interface is empty.  Is this implemented?
E.g. `chrome.storage.local`, `chrome.storage.sync`

**Comment by tfoxy** [comment]
It seems I'm not handling nested interfaces in the type definitions. I created an issue for this: #14 .
