### ISSUE TITLE
Why using `GLOBAL` in source code?

### ISSUE THREAD

**Issue by foray1010** [tfoxy/chrome-promise#2]
What does it refer to?
If it is useful, I suggest to  use `typeof GLOBAL === 'undefined'` to check if it exists, because it causes error when using strict mode

**Comment by tfoxy** [comment]
It is used when testing in Node.js. It refers to the global object.
I replaced it with a `this` keyword.
Let me know if it works.

**Comment by foray1010** [comment]
It works now, thanks!

Have widely used in https://github.com/foray1010/Popup-my-Bookmarks/tree/deku

**Comment by tfoxy** [comment]
I'm glad that it's useful. I downloaded the extension. Never had one for bookmarks.
I like that it does not use memory when not being used.
