### ISSUE TITLE
There is a 47MB `google-chrome-stable_current_amd64.deb` in package?

### ISSUE THREAD

**Issue by amio** [tfoxy/chrome-promise#7]
https://registry.npmjs.org/chrome-promise/-/chrome-promise-2.0.0.tgz

**Comment by tfoxy** [comment]
Thanks for reporting this. Didn't realize that. Travis is downloading chrome and then publishing to npm with this file included.

I will fix it later this day.

**Comment by tfoxy** [comment]
Fixed in v2.0.1

**Comment by amio** [comment]
Thanks 👍
