### ISSUE TITLE
Consider remove requirement of creating object

### ISSUE THREAD

**Issue by amio** [tfoxy/chrome-promise#8]
Since there's no option for `new ChromePromise()`, how about let user directly use `window.ChromePromise` or `import cp from 'chrome-promise'`?

**Comment by amio** [comment]
Oops, my mistake, there is an option object >.<

**Comment by tfoxy** [comment]
There is an options object. But most people using this library will never use the options.

So I think it's better to provide an instance of ChromePromise as default and if someone wants to use the constructor, then it can be imported from 'chrome-promise/constructor'.

I can make the changes on the weekend.

**Comment by tfoxy** [comment]
Fixed in 797b0af2e4c4094b11175180de29685dba2971bb
