### ISSUE TITLE
Need support for Chrome 32

### ISSUE THREAD

**Issue by foray1010** [tfoxy/chrome-promise#9]
Hi @tfoxy,

wanna ask if we can support Chrome 32, my extension already have a large user base and I don't want a sudden increase of min chrome version which may result in decreasing my user numbers

I am available to make PR and test it using Chrome 32, I think we just need to remove the rest parameters

**Comment by tfoxy** [comment]
No problem. If you make a PR I will merge it and release a new version.

**Comment by foray1010** [comment]
thanks, I will do it on the weekend
